### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by sbonsing** [mtgeekman/Home_Assistant_NeoSmartBlinds#20]
component not working.
im pretty sure its because of the following

https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes.

**Comment by mtgeekman** [comment]
What version of the integration are you running?

**Comment by igrybkov** [comment]
I just got my Neo equipment and faced the same issue while trying to setup the integration.

What I did to reproduce:
- Added custom repository to HACS that points to this repo
- Installed integration with HACS
- Rebooted
- Added config entry
- Validated configuration

It didn't work this way and complained about missing integration. As far as I understand (I didn't really play with it more than necessary to make it work), that's because HACS unpacked archive into subdirectory of a directory, so files were in something like `config/custom_components/neosmartblinds/neosmartblinds` and this double path doesn't work for home assistant.
To figure this out though, I already added config record into my `configuration.yaml` and this caused home assistant to fail to restart from the UI because configuration was invalid due to missing component.
Noting this because I spend some time debugging believing that it restarts and problem remains while the restart itself just didn't happen.

So to fix it I had to
- remove integration through HACS
- clone the repo into `config/custom_components/neosmartblinds`
- comment integration in config
- restart home assistant
- uncomment integration
- restart it again

After that everything works as expected.
