### ISSUE TITLE
Calling Service "Cover: Stop" Results in Blinds Moving to Favorite Position

### ISSUE THREAD

**Issue by BillyFKidney** [mtgeekman/Home_Assistant_NeoSmartBlinds#39]
```
service: cover.stop_cover
data: {}
target:
  entity_id: cover.living_room_blinds
```

Calling this service when the blinds are not moving results in our blinds moving to Favorite 1.
Is this expected behavior?

If the blinds are currently in motion, the service does stop them as expected.

**Comment by Bacichetti** [comment]
Billy,

Yes, that's the expected behaviour for the motor you have. Motor codes 'bf' and 'tb'.
It's not the expected behaviour for any other brand currently compatible with Neo Smart Blinds.

You can reproduce it using a handheld remote.
For the same command, STOP, the motor will
- move to the favourite position if it's not moving
- stop if the motor is moving

So that you know, some variations of your motor will not stop when the STOP button is pressed while the motor moves to the favourite position. If the motor is in motion to the upper and lower limits, it should always stop when the STOP button is pressed.
